apiVersion: v1
kind: Secret
metadata:
  name: api-key-secret
  namespace: k8s-deployment-restarter
type: Opaque
data:
  API_KEY: YXBpLWtleS0xMjMK # echo "api-key-123" | base64 >>>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment-restarter
  namespace: k8s-deployment-restarter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-deployment-restarter
  template:
    metadata:
      labels:
        app: k8s-deployment-restarter
    spec:
      serviceAccountName: k8s-deployment-restarter-account
      containers:
        - name: k8s-deployment-restarter
          image: ghcr.io/cloudnative-zoo/k8s-deployment-restarter:master
          ports:
            - containerPort: 8000
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment-restarter
  namespace: k8s-deployment-restarter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: k8s-deployment-restarter
---
