apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-deployment-restarter-account
  namespace: k8s-deployment-restarter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-deployment-restarter-clusterrole
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-deployment-restarter-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: k8s-deployment-restarter-account
    namespace: k8s-deployment-restarter
roleRef:
  kind: ClusterRole
  name: k8s-deployment-restarter-clusterrole
  apiGroup: rbac.authorization.k8s.io
---